# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.mjs — do not edit by hand.
class Statica < Formula
  desc "Powered HTML static site generator"
  homepage "https://github.com/akaizn-junior/statica"
  license "MIT"
  version "0.18.1"

  on_macos do
    on_arm do
      url "https://github.com/akaizn-junior/statica/releases/download/v0.18.1/statica-aarch64-apple-darwin"
      sha256 "d9444a604547a2a25185e87a2ffabf4944e610324701f9a655a89474ba45ae1a"
    end
    on_intel do
      url "https://github.com/akaizn-junior/statica/releases/download/v0.18.1/statica-x86_64-apple-darwin"
      sha256 "4c397de5b8853f448f60522f060aa9af77b43d4fd3aa3a630418a6e97adeb300"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/akaizn-junior/statica/releases/download/v0.18.1/statica-aarch64-unknown-linux-gnu"
      sha256 "5c5bd43bb6944ae6c7140121486cbe3c14ea90a16d4ccdc6a8fca7f424e2e82f"
    end
    on_intel do
      url "https://github.com/akaizn-junior/statica/releases/download/v0.18.1/statica-x86_64-unknown-linux-gnu"
      sha256 "07937d56e1feb64cf98adf96d6cb54b571bd48f86f89cc925820680451449bf0"
    end
  end

  def install
    bin.install "statica-aarch64-apple-darwin" => "statica" if OS.mac? && Hardware::CPU.arm?
    bin.install "statica-x86_64-apple-darwin" => "statica" if OS.mac? && Hardware::CPU.intel?
    bin.install "statica-aarch64-unknown-linux-gnu" => "statica" if OS.linux? && Hardware::CPU.arm?
    bin.install "statica-x86_64-unknown-linux-gnu" => "statica" if OS.linux? && Hardware::CPU.intel?
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/statica -v")
  end
end
