# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.mjs — do not edit by hand.
class Statica < Formula
  desc "Powered HTML static site generator"
  homepage "https://github.com/akaizn-junior/statica"
  license "MIT"
  version "0.32.0"

  on_macos do
    on_arm do
      url "https://github.com/akaizn-junior/statica/releases/download/v0.32.0/statica-aarch64-apple-darwin"
      sha256 "df4c16310ba9626bb2080eecb9415a34c5dcec15f0e1479a6b9b193173d4455f"
    end
    on_intel do
      url "https://github.com/akaizn-junior/statica/releases/download/v0.32.0/statica-x86_64-apple-darwin"
      sha256 "05c3910f641fc1cf690297437d18a6bf8aa454d80b90ca37c6c05191ab6b75f3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/akaizn-junior/statica/releases/download/v0.32.0/statica-aarch64-unknown-linux-gnu"
      sha256 "595472e0212b9a62a706921d57056d48afb8a6ce45e646fb5861676e77a5a3ec"
    end
    on_intel do
      url "https://github.com/akaizn-junior/statica/releases/download/v0.32.0/statica-x86_64-unknown-linux-gnu"
      sha256 "5c3949d3cd5ab257d059501530afd7ca72756248b34a8086a7148cb5a66a47ea"
    end
  end

  def install
    bin.install "statica-aarch64-apple-darwin" => "statica" if OS.mac? && Hardware::CPU.arm?
    bin.install "statica-x86_64-apple-darwin" => "statica" if OS.mac? && Hardware::CPU.intel?
    bin.install "statica-aarch64-unknown-linux-gnu" => "statica" if OS.linux? && Hardware::CPU.arm?
    bin.install "statica-x86_64-unknown-linux-gnu" => "statica" if OS.linux? && Hardware::CPU.intel?
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/statica -v")
  end
end
