# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.mjs — do not edit by hand.
class Statica < Formula
  desc "Powered HTML static site generator"
  homepage "https://github.com/akaizn-junior/statica"
  license "MIT"
  version "0.34.0"

  on_macos do
    on_arm do
      url "https://github.com/akaizn-junior/statica/releases/download/v0.34.0/statica-aarch64-apple-darwin"
      sha256 "47c9423a4e2c09b39a889f139cfcb77179ccf87e98dd6ea73f29680f707c7ba9"
    end
    on_intel do
      url "https://github.com/akaizn-junior/statica/releases/download/v0.34.0/statica-x86_64-apple-darwin"
      sha256 "05c5b2b6a6665532f783ea3df49a8966d8c7e63ffce4785d086ace9832b4dbce"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/akaizn-junior/statica/releases/download/v0.34.0/statica-aarch64-unknown-linux-gnu"
      sha256 "c907ec686b0cd078544f27fe9acaa179f5ec288ce5af01b5e1e5cd8004a40c91"
    end
    on_intel do
      url "https://github.com/akaizn-junior/statica/releases/download/v0.34.0/statica-x86_64-unknown-linux-gnu"
      sha256 "03dc2629dd4aba78f9adfcb07e27f191280c4fe0bc108edf04b6a271399601c1"
    end
  end

  def install
    bin.install "statica-aarch64-apple-darwin" => "statica" if OS.mac? && Hardware::CPU.arm?
    bin.install "statica-x86_64-apple-darwin" => "statica" if OS.mac? && Hardware::CPU.intel?
    bin.install "statica-aarch64-unknown-linux-gnu" => "statica" if OS.linux? && Hardware::CPU.arm?
    bin.install "statica-x86_64-unknown-linux-gnu" => "statica" if OS.linux? && Hardware::CPU.intel?
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/statica -v")
  end
end
